# Generated by Django 5.0.6 on 2024-06-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("items_name", models.CharField(max_length=100)),
                ("itmes_price", models.IntegerField()),
                ("items_description", models.CharField(max_length=50)),
                (
                    "items_type",
                    models.CharField(
                        choices=[
                            ("Veg", "Veg"),
                            ("Non-Veg", "Non-Veg"),
                            ("Egg", "Egg"),
                        ],
                        max_length=150,
                    ),
                ),
                ("items_image", models.ImageField(upload_to="")),
            ],
        ),
    ]
