# Generated by Django 5.0.6 on 2024-06-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="items", old_name="itmes_price", new_name="items_price",
        ),
        migrations.RemoveField(model_name="items", name="id",),
        migrations.AddField(
            model_name="items",
            name="items_id",
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
