# Generated by Django 5.0.6 on 2024-06-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "master",
            "0002_rename_itmes_price_items_items_price_remove_items_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="items_description",
            field=models.CharField(max_length=350),
        ),
    ]
